Framework/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});

Route::resource('favorites', 'FavoritesController');
Route::resource('payments', 'PaymentsController');
Route::resource('users', 'UsersController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Framework/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'name', 'password', 'age'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

Framework/app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\User;
use App\Http\Requests\UsersUpdateRequest;


class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $post = User::All();
        return view('user.list', ['users' => $post]);
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users =  User::where('id',$id)->first();
        return view('user.edit', ['usuario' => $users]);
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UsersUpdateRequest $request, $id)
    {
        User::findOrFail($id);

        User::where('id', $id)
            ->update([
                'name' => $request['name'],
                'age' => $request['age']
            ]);
        return redirect()->route('users.index');
        //
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = User::findOrFail($id);

        $favoritos = new FavoritesController();
        $favoritos->deleteRecursiveData($item->id);

        $payments = new PaymentsController();
        $payments->deleteRecursiveData($item->id);

        $item->delete();

        return redirect()->route('users.index');
        //
    }
}

Framework/resources/views/user/edit.blade.php
@extends('templete.template')
@extends('comun.head')

@section('head_custom')
    {!! Html::style('plugins/jquery-ui/jquery-ui.css') !!}

@stop

@extends('comun.navbar')
@extends('comun.menu')

@section('contenido')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Edit User</h4>
                        </div>
                        <div class="content">

                            {!!Form::model($usuario,['route'=>['users.update',$usuario], 'method'=>'PUT', 'id'=>'perfil-form', 'files' => true])!!}
                                @include('user.form')
                                {!!Form::hidden('age_user', $usuario->age,['id'=>'age_user'])!!}
                            {!!Form::close()!!}
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card card-user">
                        <div class="image">
                            <img src="https://ununsplash.imgix.net/photo-1431578500526-4d9613015464?fit=crop&fm=jpg&h=300&q=75&w=400" alt="..."/>
                        </div>
                        <div class="content">
                            <div class="author">
                                <a href="#">
                                    {{ Html::image('images/faces/face-7.jpg', 'a picture', array('class' => 'avatar border-gray')) }}

                                    <h4 class="title">{{$usuario['name']}}<br /></h4>
                                </a>
                            </div>
                        </div>
                        <hr>
                        <div class="text-center">
                            <button href="#" class="btn btn-simple"><i class="fa fa-facebook-square"></i></button>
                            <button href="#" class="btn btn-simple"><i class="fa fa-twitter"></i></button>
                            <button href="#" class="btn btn-simple"><i class="fa fa-google-plus-square"></i></button>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>



@stop

@extends('comun.js')

@section('js_custom')

    {!! Html::script('admin/plugins/jquery-ui/jquery-ui.js') !!}

    <!-- bootstrap-wysiwyg -->
    <script>
        $(document).ready(function() {
            $("#age option[value='"+$('#age_user').val()+"']").prop('selected', true);
        });
    </script>



@stop

Framework/resources/views/user/form.blade.php
        <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label>Name</label>
                {!!Form::text('name',null,['class'=>'form-control','placeholder'=> 'First Name' ])!!}.
                @if ($errors->has('name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </span>
                @endif
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label>Age</label>
                <select id="age" name="age">
                    <option value="18">18</option>
                    <option value="19">19</option>
                    <option value="20">20</option>
                    <option value="21">21</option>
                    <option value="22">22</option>
                    <option value="23">23</option>
                    <option value="24">24</option>
                    <option value="25">25</option>
                    <option value="26">26</option>
                    <option value="27">27</option>
                    <option value="28">28</option>
                    <option value="29">29</option>
                    <option value="30">30</option>
                </select>
                @if ($errors->has('age'))
                    <span class="help-block">
                                        <strong>{{ $errors->first('age') }}</strong>
                                    </span>
                @endif
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-info btn-fill pull-right">Update</button>

    <div class="clearfix"></div>

Framework/resources/views/user/list.blade.php
@extends('templete.template')
@extends('comun.head')

@section('head_custom')
    {!! Html::style('plugins/dataTables/dataTables.bootstrap.css') !!}

@stop

@extends('comun.navbar')
@extends('comun.menu')

@section('contenido')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <p class="text-muted font-13 m-b-30">
                        {!!link_to_route('register', $title = 'New User', $parameters = array(), $attributes = ['class'=>'btn btn-default'])!!}
                    </p>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Age</th>
                                <th>Edit</th>
                                <th>Delete</th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($users as $value)
                                <tr class="odd gradeX">
                                    <th>{{ $value->name}}</th>
                                    <th>{{ $value->age}}</th>

                                    <td class="center">{!!link_to_route('users.edit', $title = 'Edit', $parameters = $value->id, $attributes = [])!!}</td>

                                    <td class="center alert">
                                        <form action="{{ route('users.destroy', $value->id) }}" method="POST">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-danger btn-fill pull-left">Delete</button>
                                        </form>
                                    </td>

                                </tr>
                            @endforeach

                            </tbody>

                        </table>

                    </div>


                </div>

            </div>
        </div>
    </div>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
@stop

@extends('comun.js')

@section('js_custom')

    {!! Html::script('plugins/dataTables/jquery.dataTables.js') !!}
    {!! Html::script('plugins/dataTables/dataTables.bootstrap.js') !!}

    <script>
        $(document).ready(function () {
            $('#dataTables-example').dataTable();
        });

    </script>
@stop