Framework/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});

Route::resource('favorites', 'FavoritesController');
Route::resource('payments', 'PaymentsController');
Route::resource('users', 'UsersController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Framework/app/Models/Favorites.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Favorites extends Model
{

    protected $table = 'favorites';
    protected  $fillable = [
        'user_id', 'user_favorite_id'
    ];
    //
}

Framework/app/Http/Controllers/FavoritesController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use App\Http\Requests\FavoritesCreateRequest;
use App\Models\Favorites;




class FavoritesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $post = Favorites::select('favorites.id', 'users.name as user_name', 'users2.name as user_favorite_name')
            ->join('users', 'users.id', '=', 'favorites.user_id')
            ->join('users as users2', 'users2.id', '=', 'favorites.user_favorite_id')
            ->get();
        return view('favorites.list', ['favorites' => $post]);
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $post = User::All();
        return view('favorites.new', ['users' => $post]);
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FavoritesCreateRequest $request)
    {

        Favorites::create([
            'user_id' => $request['user_id'],
            'user_favorite_id' => $request['user_favorite_id'],
        ]);

        return redirect()->route('favorites.index');

        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data =  Favorites::where('id',$id)->first();

        $users = User::All();
        return view('favorites.edit', ['data' => $data, 'users' => $users]);
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(FavoritesCreateRequest $request, $id)
    {
        Favorites::findOrFail($id);
        User::findOrFail($request['user_id']);
        User::findOrFail($request['user_favorite_id']);

        Favorites::where('id', $id)
            ->update([
                'user_id' => $request['user_id'],
                'user_favorite_id' => $request['user_favorite_id'],
            ]);

        return redirect()->route('favorites.index');
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Favorites::findOrFail($id);
        $item->delete();

        return redirect()->route('favorites.index');
        //
    }

    // Delete data from table when is delete a user
    public function deleteRecursiveData($id){
        Favorites::where('user_id', $id)
            ->delete();

        Favorites::where('user_favorite_id', $id)
            ->delete();

    }
}

Framework/resources/views/favorites/edit.blade.php
@extends('templete.template')
@extends('comun.head')

@section('head_custom')
    {!! Html::style('admin/plugins/jquery-ui/jquery-ui.css') !!}
@stop

@extends('comun.navbar')
@extends('comun.menu')

@section('contenido')

    {!!Form::model($data,['route'=>['favorites.update',$data], 'method'=>'PUT', 'onsubmit' => 'myFunction()', 'class'=>'form-horizontal form-label-left', 'id'=>'login-form', 'files' => true])!!}
        @include('favorites.form')
        {!!Form::hidden('select_user_value', $data->user_id,['id'=>'select_user_value'])!!}
        {!!Form::hidden('select_favorite_value', $data->user_favorite_id,['id'=>'select_favorite_value'])!!}
    {!!Form::close()!!}
@stop

@extends('comun.js')

@section('js_custom')

    {!! Html::script('admin/plugins/jquery-ui/jquery-ui.js') !!}
    <script>
        $(document).ready(function() {
            $("#user_id option[value='"+$('#select_user_value').val()+"']").prop('selected', true);
            $("#user_favorite_id option[value='"+$('#select_favorite_value').val()+"']").prop('selected', true);
        });
    </script>
@stop

Framework/resources/views/favorites/form.blade.php
<div class="x_panel">
    <div class="x_title">
        <h2>=D</h2>

        <div class="clearfix"></div>
    </div>
    <div class="x_content">

    <div class="form-group">
        {!!Form::label('user_id', 'User', ['class' => 'control-label col-md-3 col-sm-3 col-xs-12'])!!}
        <div class="col-md-9 col-sm-9 col-xs-12">
        <select name="user_id" id="user_id" class="form-control" required>
            @foreach ($users as $value)
                <option value="{{$value->id }}"> {{$value->name}}</option>
            @endforeach
        </select>
            @if ($errors->has('user_id'))
                <span class="help-block">
                        <strong>{{ $errors->first('user_id') }}</strong>
                    </span>
            @endif
        </div>
    </div>

    <div class="form-group">

        {!!Form::label('user_favorite_id', 'Favourite', ['class' => 'control-label col-md-3 col-sm-3 col-xs-12'])!!}
        <div class="col-md-9 col-sm-9 col-xs-12">
            <select name="user_favorite_id" id="user_favorite_id" class="form-control" required>
                @foreach ($users as $value)
                    <option value="{{$value->id }}"> {{$value->name}}</option>
                @endforeach
            </select>
            @if ($errors->has('user_favorite_id'))
                <span class="help-block">
                        <strong>{{ $errors->first('user_favorite_id') }}</strong>
                    </span>
            @endif
        </div>
    </div>


        <div class="ln_solid"></div>
    <div class="form-group">
        <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
            <button type="submit"   class="btn btn-success">Submit</button>
        </div>
    </div>


</div>
    </div>

Framework/resources/views/favorites/list.blade.php
@extends('templete.template')
@extends('comun.head')

@section('head_custom')
    {!! Html::style('plugins/dataTables/dataTables.bootstrap.css') !!}

@stop

@extends('comun.navbar')
@extends('comun.menu')

@section('contenido')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <p class="text-muted font-13 m-b-30">
                        {!!link_to_route('favorites.create', $title = 'New Favourite', $parameters = array(), $attributes = ['class'=>'btn btn-default'])!!}
                    </p>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                            <tr>
                                <th>User</th>
                                <th>Favourite</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach ($favorites as $value)
                                    <tr class="odd gradeX">
                                        <td>{{ $value->user_name}}</td>
                                        <td>{{ $value->user_favorite_name}}</td>

                                        <td class="center">{!!link_to_route('favorites.edit', $title = 'Edit', $parameters = $value->id, $attributes = ['class'=>''])!!}</td>
                                        <td class="center">
                                            <form action="{{ route('favorites.destroy', $value->id) }}" method="POST">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-danger btn-fill pull-left">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
@stop

@extends('comun.js')

@section('js_custom')

    {!! Html::script('plugins/dataTables/jquery.dataTables.js') !!}
    {!! Html::script('plugins/dataTables/dataTables.bootstrap.js') !!}

    <script>
        $(document).ready(function () {
            $('#dataTables-example').dataTable();
        });
    </script>
@stop

Framework/resources/views/favorites/new.blade.php
@extends('templete.template')
@extends('comun.head')

@section('head_custom')

@stop

@extends('comun.navbar')
@extends('comun.menu')

@section('contenido')
    {!!Form::open(['route'=>'favorites.store', 'method'=>'POST', 'onsubmit' => 'myFunction()', 'class'=>'form-horizontal form-label-left', 'id'=>'login-form', 'files' => true])!!}
        @include('favorites.form')
    {!!Form::close()!!}
@stop
@extends('comun.js')

@section('js_custom')


<!-- bootstrap-wysiwyg -->
<script>

</script>



@stop