Framework/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});

Route::resource('favorites', 'FavoritesController');
Route::resource('payments', 'PaymentsController');
Route::resource('users', 'UsersController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Framework/app/Models/Payments.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Payments extends Model
{
    protected $table = 'payments';
    protected  $fillable = [
        'id', 'amount', 'date'
    ];
    //
}

Framework/app/Http/Controllers/PaymentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\User;
use App\Models\Payments;
use App\Models\UserPayments;
use App\Http\Requests\PaymentCreateRequest;

class PaymentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $post = UserPayments::select('user_payments.id as user_payment_id', 'users.name', 'users.age', 'payments.amount', 'payments.date', 'payments.id as payment_id')
            ->join('users', 'users.id', '=', 'user_payments.user_id')
            ->join('payments', 'payments.id', '=', 'user_payments.payment_id')
            ->get();

        return view('payment.list', ['payments' => $post]);
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $post = User::All();
        return view('payment.new', ['users' => $post]);

        //
    }
    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store(PaymentCreateRequest $request)
    {
        User::findOrFail($request['user_id']);

        $paymentData = Payments::create([
            'amount' => $request['amount'],
            'date' => $request['date'],
        ]);


        UserPayments::create([
            'payment_id' => $paymentData->id,
            'user_id' => $request['user_id'],
        ]);

        return redirect()->route('payments.index');
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users = User::All();

        $post = UserPayments::select('user_payments.id', 'user_payments.user_id as user_payment_id', 'payments.amount', 'payments.date', 'payments.id as payment_id')
            ->where('user_payments.id', '=', $id)
            ->join('payments', 'payments.id', '=', 'user_payments.payment_id')
            ->first();
        return view('payment.edit', ['payment' => $post, 'users' => $users, 'id' => $id]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PaymentCreateRequest $request, $id)
    {
        User::findOrFail($request['user_id']);
        UserPayments::findOrFail($id);

        UserPayments::where('id', $id)
            ->update([
                'user_id' => $request['user_id']
            ]);

        Payments::where('id', $id)
            ->update([
                'amount' => $request['amount'],
                'date' => $request['date']
            ]);
        return redirect()->route('payments.index');
        //
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = UserPayments::findOrFail($id);

        Payments::where('id', $item->payment_id)
            ->delete();

        $item->delete();

        return redirect()->route('payments.index');
        //
    }
    // Delete data from table when is delete a user

    public function deleteRecursiveData($id){

        $post =  UserPayments::where('user_id',$id)
            ->get();

        foreach ($post as $values){
            Payments::where('id', $values->payment_id)
                ->delete();
        }

        UserPayments::where('user_id', $id)
            ->delete();

    }
}

Framework/resources/views/payment/edit.blade.php
@extends('templete.template')
@extends('comun.head')

@section('head_custom')
    {!! Html::style('plugins/jquery-ui/jquery-ui.css') !!}

@stop

@extends('comun.navbar')
@extends('comun.menu')

@section('contenido')

    {!!Form::model($payment,['route'=>['payments.update',$payment], 'method'=>'PUT', 'id'=>'perfil-form', 'files' => true])!!}
        @include('payment.form')
        {!!Form::hidden('user_selected', $payment->user_payment_id,['id'=>'user_selected'])!!}

    {!!Form::close()!!}

@stop

@extends('comun.js')

@section('js_custom')

    {!! Html::script('plugins/jquery-ui/jquery-ui.js') !!}

    <script>

        $(document).ready(function() {

            $("#user_id option[value='"+$('#user_selected').val()+"']").prop('selected', true);

            $( "#date" ).datepicker({
                changeMonth: true,
                changeYear: true,
                minDate: 0,
                dateFormat: "yy-mm-dd",
                yearRange: "0:+5",
            });
        });
    </script>
@stop

Framework/resources/views/payment/form.blade.php
<div class="x_panel">
    <div class="x_title">
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <div class="form-group">
            {!!Form::label('amount', 'Amount', ['class' => 'control-label col-md-3 col-sm-3 col-xs-12'])!!}

            <div class="col-md-9 col-sm-9 col-xs-12">
                {!! Form::number('amount',  null, ['required', 'min' => 1, 'class' => 'form-control']) !!}
                @if ($errors->has('amount'))
                    <span class="help-block">
                        <strong>{{ $errors->first('amount') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        <div class="form-group">
            {!!Form::label('user', 'User', ['class' => 'control-label col-md-3 col-sm-3 col-xs-12'])!!}

            <div class="col-md-9 col-sm-9 col-xs-12">
                <select name="user_id" id="user_id" class="form-control" required>
                    @foreach ($users as $value)
                        <option value="{{$value->id }}"> {{$value->name}}</option>
                    @endforeach
                </select>
                @if ($errors->has('user_id'))
                    <span class="help-block">
                        <strong>{{ $errors->first('user_id') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        <div class="form-group">
            {!!Form::label('date', 'Date', ['class' => 'control-label col-md-3 col-sm-3 col-xs-12'])!!}

            <div class="col-md-9 col-sm-9 col-xs-12">
                {!!Form::text('date', null, ['class'=>'form-control', 'id'=>'date', 'readonly'])!!}
                @if ($errors->has('date'))
                    <span class="help-block">
                        <strong>{{ $errors->first('date') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="ln_solid"></div>
        <div class="form-group">
            <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                <button type="submit"   class="btn btn-success">Submit</button>
            </div>
        </div>
    </div>
</div>

Framework/resources/views/payment/list.blade.php
@extends('templete.template')
@extends('comun.head')

@section('head_custom')
    {!! Html::style('plugins/dataTables/dataTables.bootstrap.css') !!}

@stop

@extends('comun.navbar')
@extends('comun.menu')

@section('contenido')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <p class="text-muted font-13 m-b-30">
                        {!!link_to_route('payments.create', $title = 'New Payment', $parameters = array(), $attributes = ['class'=>'btn btn-default'])!!}
                    </p>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                            <tr>
                                <th>Payment number</th>
                                <th>Amount</th>
                                <th>User</th>
                                <th>Date</th>
                                <th>Edit</th>
                                <th>Delete</th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($payments as $value)
                                <tr class="odd gradeX">
                                    <th>{{ $value->payment_id}}</th>
                                    <th>{{ $value->amount}}</th>
                                    <th>{{ $value->name}}</th>
                                    <th>{{ $value->date}}</th>

                                    <td class="center">{!!link_to_route('payments.edit', $title = 'Edit', $parameters = $value->user_payment_id, $attributes = [])!!}</td>
                                    <td class="center alert">
                                        <form action="{{ route('payments.destroy', $value->user_payment_id) }}" method="POST">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-danger btn-fill pull-left">Delete</button>
                                        </form>
                                    </td>

                                </tr>
                            @endforeach

                            </tbody>

                        </table>

                    </div>


                </div>

            </div>
        </div>
    </div>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
@stop

@extends('comun.js')

@section('js_custom')

    {!! Html::script('plugins/dataTables/jquery.dataTables.js') !!}
    {!! Html::script('plugins/dataTables/dataTables.bootstrap.js') !!}

    <script>
        $(document).ready(function () {
            $('#dataTables-example').dataTable();
        });

    </script>
@stop

Framework/resources/views/payment/new.blade.php
@extends('templete.template')
@extends('comun.head')

@section('head_custom')
    {!! Html::style('plugins/jquery-ui/jquery-ui.css') !!}

@stop

@extends('comun.navbar')
@extends('comun.menu')

@section('contenido')

    {!!Form::open(['route'=>'payments.store', 'method'=>'POST', 'onsubmit' => 'myFunction()', 'class'=>'form-horizontal form-label-left', 'id'=>'login-form', 'files' => true])!!}
    @include('payment.form')
    {!!Form::close()!!}

@stop
@extends('comun.js')
@section('js_custom')

    {!! Html::script('plugins/jquery-ui/jquery-ui.js') !!}

    <script>
        $(document).ready(function() {

            $( "#date" ).datepicker({
                changeMonth: true,
                changeYear: true,
                minDate: 0,
                yearRange: "0:+5",
                dateFormat: "yy-mm-dd"
            });
        });
    </script>





@stop